{% set name = "webhelpers2" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/WebHelpers2-{{ version }}.tar.gz
  sha256: 22b20d26778c64e899ad61a8f385266dd53e0d43e707f0cd375f1de77a0d622f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - markupsafe >=0.9.2
    - six >=1.4.0

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - {{ name }}
  commands:
    - pytest tests

about:
  home: https://webhelpers2.readthedocs.io/en/latest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Convenience functions for generating html'
  description: |
    WebHelpers2 is the successor to the widely-used WebHelpers utilities.
    It contains convenience functions to make HTML tags, process text,
    format numbers, do basic statistics, work with collections, and more.
  doc_url: https://webhelpers2.readthedocs.io/en/latest
  dev_url: https://github.com/mikeorr/WebHelpers2

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - mikeorr
